version: '3.3'

services:
    nodeserver:
        build:
            context: ./app
        container_name: app
        networks:  
          - node-network
        tty: true
        ports:
          - "5000:5000"
        depends_on:
          - db

    db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      volumes: 
        - ./mysql:/docker-entrypoint-initdb.d
      environment:  
        - MYSQL_DATABASE=nodedb
        - MYSQL_ROOT_PASSWORD=root
      networks: 
        - node-network

    nginx:
        restart: always
        build: 
            context: ./nginx
        container_name: nginx
        ports:
            - "8080:80" 
        networks:  
          - node-network
        depends_on:
          - nodeserver

networks:  
  node-network:
    driver: bridge      
